version: '3.4'

services:
  flaskapi:
    image: falbanese90/flaskapi:v2

    depends_on:
      - db
    links:
      - db
    environment:
      MYSQL_HOST: 'db'
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "5000:5000"
    expose:
      - '5000'

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
# Names our volume
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
